---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '`librerias["sector"].head(3)`'
  checked: true
- value: '`librerias["city_name"].tail(4)`'
  checked: true
- value: '`len(librerias["city_name"])`'
  checked: true
name: Una columna fuera de serie
