---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Recetas de cocina
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Datos estadísticos de un país
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Datos individualizados de sus ciudadanos
  checked: false
name: Abierto al público
