import pandas as pd
import numpy as np

librerias = pd.DataFrame([
  {'city_id': 2000010, 'prov_id': 2, 'dep_id': 2000, 'obs': np.nan, 'category': 'Librerias', 'prov_name': 'Ciudad Autónoma de Buenos Aires', 'dep_name': 'Ciudad Autónoma de Buenos Aires', 'city_name': 'Ciudad Autonoma de Buenos Aires', 'name': 'La Ley Casa Central', 'address': 'Tucumán 1471', 'floor': np.nan, 'zip_code': np.nan, 'area_code': 11.0, 'sector': 'Privado', 'update_year': 2018},
 {'city_id': 58056010, 'prov_id': 58, 'dep_id': 58056, 'obs': np.nan, 'category': 'Librerias', 'prov_name': 'Neuquén', 'dep_name': 'Lacar', 'city_name': 'San Martín de los Andes', 'name': 'Pata Libro', 'address': 'San Martin 866', 'floor': np.nan, 'zip_code': np.nan, 'area_code': 2.972, 'sector': 'Privado', 'update_year': 2018},
 {'city_id': 2000010, 'prov_id': 2, 'dep_id': 2000, 'obs': np.nan, 'category': 'Librerias', 'prov_name': 'Ciudad Autónoma de Buenos Aires', 'dep_name': 'Ciudad Autónoma de Buenos Aires', 'city_name': 'Ciudad Autonoma de Buenos Aires', 'name': 'Libria', 'address': 'Juan B. Ambrosetti 740', 'floor': np.nan, 'zip_code': np.nan, 'area_code': 11.0, 'sector': 'Privado', 'update_year': 2018},
 {'city_id': 2000010, 'prov_id': 2, 'dep_id': 2000, 'obs': np.nan, 'category': 'Librerias', 'prov_name': 'Ciudad Autónoma de Buenos Aires', 'dep_name': 'Ciudad Autónoma de Buenos Aires', 'city_name': 'Ciudad Autonoma de Buenos Aires', 'name': 'Ad-Hoc Villela Editor', 'address': 'Viamonte 1450', 'floor': np.nan, 'zip_code': np.nan, 'area_code': 11.0, 'sector': 'Privado', 'update_year': 2018},
 {'city_id': 18021020, 'prov_id': 18, 'dep_id': 18021, 'obs': np.nan, 'category': 'Librerias', 'prov_name': 'Corrientes', 'dep_name': 'Capital', 'city_name': 'Corrientes', 'name': 'La Ley Corrientes', 'address': 'La Rioja 731', 'floor': np.nan, 'zip_code': np.nan, 'area_code': 379.0, 'sector': 'Privado', 'update_year': 2018},
 {'city_id': 26021030, 'prov_id': 26, 'dep_id': 26021, 'obs': np.nan, 'category': 'Librerias', 'prov_name': 'Chubut', 'dep_name': 'Escalante', 'city_name': 'Comodoro Rivadavia', 'name': 'Libros del Viento', 'address': 'Mitre 587', 'floor': np.nan, 'zip_code': np.nan, 'area_code': np.nan, 'sector': 'Privado', 'update_year': 2018},
 {'city_id': 2000010, 'prov_id': 2, 'dep_id': 2000, 'obs': np.nan, 'category': 'Librerias', 'prov_name': 'Ciudad Autónoma de Buenos Aires', 'dep_name': 'Ciudad Autónoma de Buenos Aires', 'city_name': 'Ciudad Autonoma de Buenos Aires', 'name': 'White Rabbit (Ma. Cecilia Fernández)', 'address': 'Malabia 775', 'floor': np.nan, 'zip_code': np.nan, 'area_code': 11.0, 'sector': 'Privado', 'update_year': 2018},
 {'city_id': 70028010, 'prov_id': 70, 'dep_id': 70028, 'obs': np.nan, 'category': 'Librerias', 'prov_name': 'San Juan', 'dep_name': 'Capital', 'city_name': 'San Juan', 'name': 'Centro Educativo SRL', 'address': 'Rivadavia 81', 'floor': np.nan, 'zip_code': np.nan, 'area_code': 264.0, 'sector': 'Privado', 'update_year': 2018},
 {'city_id': 2000010, 'prov_id': 2, 'dep_id': 2000, 'obs': np.nan, 'category': 'Librerias', 'prov_name': 'Ciudad Autónoma de Buenos Aires', 'dep_name': 'Ciudad Autónoma de Buenos Aires', 'city_name': 'Ciudad Autonoma de Buenos Aires', 'name': 'Acme Agency. Sucursal Camacua.', 'address': 'Camacua 87', 'floor': np.nan, 'zip_code': np.nan, 'area_code': 11.0, 'sector': 'Privado', 'update_year': 2018},
 {'city_id': 6441030, 'prov_id': 6, 'dep_id': 6441, 'obs': np.nan, 'category': 'Librerias', 'prov_name': 'Buenos Aires', 'dep_name': 'La Plata', 'city_name': 'La Plata', 'name': 'La Ley La Plata', 'address': 'Calle 47  839', 'floor': np.nan, 'zip_code': np.nan, 'area_code': 221.0, 'sector': 'Privado', 'update_year': 2018}
 ])