---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: No se muestra nada
  checked: false
- value: Aparece una tabla
  checked: true
- value: Aparece un gráfico
  checked: false
- value: Se produce un error
  checked: false
goal: |
  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_equals
  value: TODO
name: Me estás cargando
