---
locale: es
tags: []
layout: input_bottom
editor: text
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices: []
goal: |
  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_equals
  value: type\(\s*cines\s*\)\s*
name: "¡Hay tabla!"
