---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: El primer campo representa un nombre o apodo
  checked: true
- value: El primer campo representa una edad
  checked: false
- value: El segundo campo representa la ciudad de nacimiento
  checked: false
- value: El segundo campo representa un apellido
  checked: true
- value: El tercer campo representa una fecha de nacimiento
  checked: false
name: Manteniendo las formas
